-- MySQL Script generated by MySQL Workbench
-- Sat Feb 10 20:18:44 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema PlayBasket
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `PlayBasket` ;

-- -----------------------------------------------------
-- Schema PlayBasket
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PlayBasket` DEFAULT CHARACTER SET utf8 ;
USE `PlayBasket` ;

-- -----------------------------------------------------
-- Table `PlayBasket`.`Utenti`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PlayBasket`.`Utenti` ;

CREATE TABLE IF NOT EXISTS `PlayBasket`.`Utenti` (
  `idUser` INT NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `pass` CHAR(64) NULL,
  `nome` VARCHAR(45) NULL,
  `cognome` VARCHAR(45) NULL,
  `altezza` INT NULL,
  `eta` INT NULL,
  `ruoloBasket` VARCHAR(45) NULL,
  `tipo` ENUM('Giocatore', 'Gestore', 'Proprietario') NULL,
  `vip` TINYINT NULL,
  `email` VARCHAR(45) NULL,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `idUser_UNIQUE` (`idUser` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PlayBasket`.`Campo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PlayBasket`.`Campo` ;

CREATE TABLE IF NOT EXISTS `PlayBasket`.`Campo` (
  `Nome` VARCHAR(45) NOT NULL,
  `Indirizzo` VARCHAR(45) NOT NULL,
  `NomeSocieta` VARCHAR(45) NOT NULL,
  `Tariffa` DECIMAL(3,2) UNSIGNED NOT NULL,
  `OrarioApertura` TIME NOT NULL,
  `OrarioChiusura` TIME NOT NULL,
  `Foto` LONGBLOB NOT NULL,
  `Proprietario` VARCHAR(45) NOT NULL,
  `Iban` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Nome`, `Indirizzo`),
  INDEX `fk_Campo_Utenti_idx` (`Proprietario` ASC) VISIBLE,
  CONSTRAINT `fk_Campo_Utenti`
    FOREIGN KEY (`Proprietario`)
    REFERENCES `PlayBasket`.`Utenti` (`username`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PlayBasket`.`RichiestaCampo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PlayBasket`.`RichiestaCampo` ;

CREATE TABLE IF NOT EXISTS `PlayBasket`.`RichiestaCampo` (
  `Nome` INT NOT NULL,
  `Indirizzo` VARCHAR(45) NOT NULL,
  `Tariffa` DECIMAL(3,2) UNSIGNED NOT NULL,
  `OrarioApertura` TIME NOT NULL,
  `OrarioChiusura` TIME NOT NULL,
  `NomeSocieta` VARCHAR(45) NOT NULL,
  `Foto` LONGBLOB NOT NULL,
  `Proprietario` VARCHAR(45) NOT NULL,
  `iban` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Nome`, `Indirizzo`),
  INDEX `fk_RichiestaCampo_Utenti1_idx` (`Proprietario` ASC) VISIBLE,
  CONSTRAINT `fk_RichiestaCampo_Utenti1`
    FOREIGN KEY (`Proprietario`)
    REFERENCES `PlayBasket`.`Utenti` (`username`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PlayBasket`.`RichiestaPartita`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PlayBasket`.`RichiestaPartita` ;

CREATE TABLE IF NOT EXISTS `PlayBasket`.`RichiestaPartita` (
  `NomeCampo` VARCHAR(45) NOT NULL,
  `IndirizzoCampo` VARCHAR(45) NOT NULL,
  `OrarioInizio` TIME NOT NULL,
  `Creatore` VARCHAR(45) NOT NULL,
  `Durata` INT UNSIGNED NOT NULL,
  `NumGiocatori` INT UNSIGNED NOT NULL,
  `data` DATE NOT NULL,
  PRIMARY KEY (`NomeCampo`, `IndirizzoCampo`, `OrarioInizio`),
  INDEX `fk_RichiestaPartita_Utenti1_idx` (`Creatore` ASC) VISIBLE,
  CONSTRAINT `fk_RichiestaPartita_Campo1`
    FOREIGN KEY (`NomeCampo` , `IndirizzoCampo`)
    REFERENCES `PlayBasket`.`Campo` (`Nome` , `Indirizzo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_RichiestaPartita_Utenti1`
    FOREIGN KEY (`Creatore`)
    REFERENCES `PlayBasket`.`Utenti` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PlayBasket`.`Partita`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PlayBasket`.`Partita` ;

CREATE TABLE IF NOT EXISTS `PlayBasket`.`Partita` (
  `NomeCampo` VARCHAR(45) NOT NULL,
  `Indirizzocampo` VARCHAR(45) NOT NULL,
  `OrarioInizio` TIME NOT NULL,
  `Creatore` VARCHAR(45) NOT NULL,
  `Durata` INT UNSIGNED NOT NULL,
  `NumGiocatori` INT UNSIGNED NOT NULL,
  `Data` DATE NOT NULL,
  PRIMARY KEY (`NomeCampo`, `Indirizzocampo`, `OrarioInizio`),
  INDEX `fk_Partita_Utenti1_idx` (`Creatore` ASC) VISIBLE,
  CONSTRAINT `fk_Partita_Utenti1`
    FOREIGN KEY (`Creatore`)
    REFERENCES `PlayBasket`.`Utenti` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Partita_Campo1`
    FOREIGN KEY (`NomeCampo` , `Indirizzocampo`)
    REFERENCES `PlayBasket`.`Campo` (`Nome` , `Indirizzo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PlayBasket`.`Partecipazione`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PlayBasket`.`Partecipazione` ;

CREATE TABLE IF NOT EXISTS `PlayBasket`.`Partecipazione` (
  `NomeCampo` VARCHAR(45) NOT NULL,
  `IndirizzoCampo` VARCHAR(45) NOT NULL,
  `OrarioInizio` TIME NOT NULL,
  `Partecipante` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`NomeCampo`, `IndirizzoCampo`, `OrarioInizio`, `Partecipante`),
  INDEX `fk_Partecipazione_Utenti1_idx` (`Partecipante` ASC) VISIBLE,
  CONSTRAINT `fk_Partecipazione_Partita1`
    FOREIGN KEY (`NomeCampo` , `IndirizzoCampo` , `OrarioInizio`)
    REFERENCES `PlayBasket`.`Partita` (`NomeCampo` , `Indirizzocampo` , `OrarioInizio`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Partecipazione_Utenti1`
    FOREIGN KEY (`Partecipante`)
    REFERENCES `PlayBasket`.`Utenti` (`username`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SET SQL_MODE = '';
DROP USER IF EXISTS user;
SET SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
CREATE USER 'user' IDENTIFIED BY 'user';

GRANT ALL ON `PlayBasket`.* TO 'user';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
